main.o: main.cpp statmh.hpp statdistros.hpp \
 /scratch/bejb/opt/rngstreams/include/RngStream.h mhexamples.hpp
mhexamples.o: mhexamples.cpp statmh.hpp statdistros.hpp \
 /scratch/bejb/opt/rngstreams/include/RngStream.h mhexamples.hpp
my_stat.o: my_stat.cpp my_stat.h statdistros.hpp \
 /scratch/bejb/opt/rngstreams/include/RngStream.h
statdistros.o: statdistros.cpp statdistros.hpp \
 /scratch/bejb/opt/rngstreams/include/RngStream.h
statmh.o: statmh.cpp statmh.hpp statdistros.hpp \
 /scratch/bejb/opt/rngstreams/include/RngStream.h
testing_main.o: testing_main.cpp my_stat.h statmh.hpp statdistros.hpp \
 /scratch/bejb/opt/rngstreams/include/RngStream.h
