main.o: main.cpp \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trans.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_cblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_spblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapacke.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solver.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dss.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_pardiso.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_rci.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_service.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dfti.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trig_transforms.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_poisson.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solvers_ee.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 statmh.hpp statdistros.hpp mhexamples.hpp
mhexamples.o: mhexamples.cpp \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trans.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_cblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_spblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapacke.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solver.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dss.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_pardiso.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_rci.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_service.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dfti.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trig_transforms.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_poisson.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solvers_ee.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 statmh.hpp statdistros.hpp mhexamples.hpp
my_stat.o: my_stat.cpp my_stat.h statdistros.hpp
statdistros.o: statdistros.cpp \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trans.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_cblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_spblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapacke.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solver.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dss.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_pardiso.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_rci.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_service.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dfti.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trig_transforms.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_poisson.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solvers_ee.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 statdistros.hpp
statmh.o: statmh.cpp \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trans.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_cblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_spblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapacke.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solver.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dss.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_pardiso.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_rci.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_service.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dfti.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trig_transforms.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_poisson.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solvers_ee.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 statmh.hpp statdistros.hpp
testing_main.o: testing_main.cpp my_stat.h statmh.hpp statdistros.hpp \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_blas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trans.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_cblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_spblas.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapacke.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solver.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dss.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_pardiso.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_rci.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_service.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vml_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_vsl_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_defines.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_functions.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_df_types.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_dfti.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_trig_transforms.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_poisson.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_solvers_ee.h \
 /hpc_apps/intel/composer_xe_2013_sp1.0.080/mkl/include/mkl_lapack.h
main.o: main.cpp statmh.hpp statdistros.hpp
mhexamples.o: mhexamples.cpp statmh.hpp statdistros.hpp
my_stat.o: my_stat.cpp my_stat.h statdistros.hpp
statdistros.o: statdistros.cpp statdistros.hpp
statmh.o: statmh.cpp statmh.hpp statdistros.hpp
testing_main.o: testing_main.cpp my_stat.h statmh.hpp statdistros.hpp
main.o: main.cpp statmh.hpp statdistros.hpp /cluster/prod/include/RngStream.h \
 mhexamples.hpp
mhexamples.o: mhexamples.cpp statmh.hpp statdistros.hpp \
 /cluster/prod/include/RngStream.h mhexamples.hpp
my_stat.o: my_stat.cpp my_stat.h statdistros.hpp \
 /cluster/prod/include/RngStream.h
statdistros.o: statdistros.cpp statdistros.hpp /cluster/prod/include/RngStream.h
statmh.o: statmh.cpp statmh.hpp statdistros.hpp /cluster/prod/include/RngStream.h
testing_main.o: testing_main.cpp my_stat.h statmh.hpp statdistros.hpp \
 /cluster/prod/include/RngStream.h
main.o: main.cpp statmh.hpp statdistros.hpp /cluster/prod/include/RngStream.h \
 mhexamples.hpp
mhexamples.o: mhexamples.cpp statmh.hpp statdistros.hpp \
 /cluster/prod/include/RngStream.h mhexamples.hpp
my_stat.o: my_stat.cpp my_stat.h statdistros.hpp \
 /cluster/prod/include/RngStream.h
statdistros.o: statdistros.cpp statdistros.hpp /cluster/prod/include/RngStream.h
statmh.o: statmh.cpp statmh.hpp statdistros.hpp /cluster/prod/include/RngStream.h
testing_main.o: testing_main.cpp my_stat.h statmh.hpp statdistros.hpp \
 /cluster/prod/include/RngStream.h
